### ISSUE TITLE
Naming naming naming :-) 

### ISSUE THREAD

**Issue by ktoso** [slashmo/gsoc-swift-tracing#12]
At some point once we have enough examples, let us gather prior art of names of the bits pieces and settle on names we'd like to stick to.

**Comment by slashmo** [comment]
We (@ktoso & I) [discussed naming](https://docs.google.com/document/d/1fkrlFYaxY3-P-ERuoEQNbi5pNdVdIP2z5Wqv6NiY_RE) and came to the following conclusions:

## BaggageContext

`Context` is too general and will collide with existing library types (e.g. Lambda.Context, NIO’s Channel Handler Contexts, and more plain “context” types in various libraries we looked at)
- [x] Rename `Context` to `BaggageContext` (prior art from the [“tracing plane” paper](https://cs.brown.edu/~jcmace/papers/mace18universal.pdf))
- [x] Rename `ContextKey` to `BaggageContextKey`
- [x] Replace `inject(_:Key.Type, value:Key.Value)` and `extract(_:Key.Type)` by get/set subscript

### Argument naming/positioning

In order to propagate baggage through functions it may (very often) be necessary to pass it explicitly. We provide the following style guidance about what the “most Swifty” way of dealing with context is:

- Assuming the general parameter ordering of Swift function is as follows (except DSL exceptions):
  1. Required non-function parameters
  2. Defaulted non-function parameters
  3. Required function parameters
  4. Defaulted function parameters
- Context should be: the last parameter in the required non-function parameters group in a function declaration.
- This way when reading the call side, users can simply ignore the context and the method remains “Swifty”.

Example: `func request(_ url: URL, context: BaggageContext)`

#### Existing context argument

If a function or library/framework already passes around context for other library needs please follow these guidelines:

1. Try to add the BaggageContext as a property baggage to your own context type, so that the call side for your users becomes context.baggage 
2. If you cannot or don’t want to add a property to your context type, pass along the BaggageContext as an additional argument called baggage

Example: `Lamda.Context`, `ChannelHandlerContext`

## Instrument

- `InstrumentationMiddleware` is confusing, because middleware is already an established term with a totally different meaning
- Tracer is tracing-specific, but we wan’t to support all kinds of cross-cutting tools
- We intend to build Tracer types as “users” of context and allow inserting tracer specific calls using instruments; rather than phrasing all words around tracing itself; this allows for other systems, such as metrics etc, to use the same “cutpoints” as trace points need
- We may consider prefixing the Instrument types somehow if necessary to avoid conflicts. However it’s important to keep in mind that those APIs very rarely going to be visible in normal day to day development
- [x] Rename `InstrumentationMiddlewareProtocol` to `InstrumentProtocol`
- [x] Rename `InstrumentationMiddleware` to `Instrument`
- [x] Rename `MultiplexInstrumentationMiddleware` to `MultiplexInstrument`
