### ISSUE TITLE
Compile use cases on CI

### ISSUE THREAD

**Issue by slashmo** [slashmo/gsoc-swift-tracing#15]
Now that the number of use cases is growing we might want to start adding them to the CI pipeline. @ktoso Do you think this makes sense? Or should we rather write separate integration tests?

**Comment by ktoso** [comment]
The question is about how we’d assert anything in “apps”, integration tests are definitely something we should do but not sure if they’d help with the current samples. Let’s at least make sure they compile via CI checks for now perhaps?

Integration tests I think we can definitely do though, but perhaps that would be a normal test in which we hook a “test tracer” and run some code snippet using “real” libraries (eg the http client and NIO handlers) and see that things got traced there. 

So that’s be good to do once we have the next step done that you’re working on now. I could also help setting up the infra for this if you want

**Comment by slashmo** [comment]
> The question is about how we’d assert anything in “apps”

How about `assert`ing on the results? So instead of printing the headers after injecting, doing an `assert(headers == expectedHeaders)`?

> and see that things got traced there

+1

> I could also help setting up the infra for this if you want

That’d be great!

**Comment by ktoso** [comment]
Synced up on this, plan of record here is:

- let's at least `compile` the `UseCases`
- we'll do `IntegrationTests` soon, once we have the NIO handlers and have a sample with HTTPClient -- the integration test will actually bind a server and run things etc.
