### ISSUE TITLE
Consider InstrumentationSystem (?) similar to MetricsSystem et al

### ISSUE THREAD

**Issue by ktoso** [slashmo/gsoc-swift-tracing#47]
Libraries will often need to pull an instrument "out of thin air" in a similar way as metrics have to be pulled out sometimes.

We should offer something similar to https://github.com/apple/swift-metrics#selecting-a-metrics-backend-implementation-applications-only

Naming will evolve here but something like `InstrumentationSystem` to be consistent with Metrics and logging perhaps?
We should also think how it relates to tracing; would we allow e.g. `InstrumentationSystem.instrument` and also `InstrumentationSystem.tracer` (where a tracer is-a instrument but not all usages need a tracer etc.)

**Comment by slashmo** [comment]
While working on this I noticed that the current shape of `InstrumentProtocol` with its associated types `InjectInto` & `ExtractFrom` prohibits us from setting up a singleton instance to be bootstrapped, as we can't know upfront what the user will bootstrap the system with (so what's the properties type?). 

Also, it's definitely possible for a system to use different technologies (HTTP, gRPC, ...) being instrumented by the same cross-cutting tool. That's why it probably makes sense to not have the `Instrument` be generic over the `InjectInto`/`ExtractFrom` types, but rather to move this responsibility somewhere else.

*I'll open a draft PR of how this could look like.*
